#ifndef __FLASH_H
#define __FLASH_H

#include "stdint.h"

#define FLASH_FRAME_SIZE 8
#define FLASH_DATA_BUF_SIZE 256
#define FLASH_ADDR_SIZE 3
#define FLASH_CMD_BUF_SIZE 1
#define FLASH_SAVE_BUF_SIZE 256
#define FLASH_SEND_BUF_SIZE 256

#define FLASH_TO_LCD_BUF_SIZE 256

#define FLASH_PROGRAM_PAGE_MAX 256
#define FLASH_HEADER_BUF_SIZE 256

#define FLASH_FRAME_TOKEN_WRITE 0
#define FLASH_FRAME_TOKEN_READ 1

#define FLASH_CMD_WRITE_ENABLE 0X06
#define FLASH_CMD_WRITE_DISABLE 0X04
#define FLASH_CMD_Read_Status_Register1 0X05
#define FLASH_CMD_Read_Status_Register2 0X35
#define FLASH_CMD_Read_Status_Register3 0X15
#define FLASH_CMD_Write_Status_Register 0X01
#define FLASH_CMD_Page_Program 0X02
#define FLASH_CMD_Quad_Page_Program 0X32
#define FLASH_CMD_BLOCK_ERASE_64 0XD8
#define FLASH_CMD_BLOCK_ERASE_32 0X52
#define FLASH_CMD_SECTOR_ERASE_4 0X20
#define FLASH_CMD_READ_DATA 0X03
#define FLASH_CMD_FAST_READ 0X0B

#define FLASH_MSG_FRAME_BUF_SIZE 32

#define FLASH_CMD_INVAL 0XFF
#define FLASH_ADDR_INVAL 0XFFFFFFFF

#define FLASH_ADDR_BACKGROUND_TEST 0X00000000
#define FLASH_ADDR_BACKGROUND_SUB 0X00010000

#define FLASH_1K_SIZE 0X0400
#define FLASH_2K_SIZE 0X0800
#define FLASH_4K_SIZE 0X1000
#define FLASH_5K_SIZE 0X1400
#define FLASH_8K_SIZE 0X2000
#define FLASH_9K_SIZE 0X2400
#define FLASH_10K_SIZE 0X2800
#define FLASH_16K_SIZE 0X4000
#define FLASH_32K_SIZE 0X8000
#define FLASH_64K_SIZE 0X10000

#define FLASH_ADDR_MENU_1 0X00020000
#define FLASH_ADDR_MENU_1_ADD (FLASH_ADDR_MENU_1 + FLASH_64K_SIZE)

// BOT LEFT
#define FLASH_ADDR_LO 0X00040000
#define FLASH_ADDR_PO (FLASH_ADDR_LO + FLASH_32K_SIZE)
#define FLASH_ADDR_R_X (FLASH_ADDR_PO + FLASH_32K_SIZE)

// BOT RIGHT
#define FLASH_ADDR_TONE 0X00060000
#define FLASH_ADDR_TONE_2 (FLASH_ADDR_TONE + FLASH_32K_SIZE)
#define FLASH_ADDR_VOL (FLASH_ADDR_TONE_2 + FLASH_32K_SIZE)
#define FLASH_ADDR_VOL_2 (FLASH_ADDR_VOL + FLASH_32K_SIZE)

// TOP LEFT
#define FLASH_ADDR_DSD_64 0x00080000
#define FLASH_ADDR_DSD_128 (FLASH_ADDR_DSD_64 + FLASH_32K_SIZE)
#define FLASH_ADDR_DSD_256 (FLASH_ADDR_DSD_128 + FLASH_32K_SIZE)
#define FLASH_ADDR_DSD_512 (FLASH_ADDR_DSD_256 + FLASH_32K_SIZE)
#define FLASH_ADDR_PCM_44 (FLASH_ADDR_DSD_512 + FLASH_32K_SIZE)
#define FLASH_ADDR_PCM_48 (FLASH_ADDR_PCM_44 + FLASH_32K_SIZE)
#define FLASH_ADDR_PCM_88 (FLASH_ADDR_PCM_48 + FLASH_32K_SIZE)
#define FLASH_ADDR_PCM_96 (FLASH_ADDR_PCM_88 + FLASH_32K_SIZE)
#define FLASH_ADDR_PCM_176 (FLASH_ADDR_PCM_96 + FLASH_32K_SIZE)
#define FLASH_ADDR_PCM_192 (FLASH_ADDR_PCM_176 + FLASH_32K_SIZE)
#define FLASH_ADDR_PCM_352 (FLASH_ADDR_PCM_192 + FLASH_32K_SIZE)
#define FLASH_ADDR_PCM_384 (FLASH_ADDR_PCM_352 + FLASH_32K_SIZE)
#define FLASH_ADDR_PCM_705 (FLASH_ADDR_PCM_384 + FLASH_32K_SIZE)
#define FLASH_ADDR_PCM_768 (FLASH_ADDR_PCM_705 + FLASH_32K_SIZE)

// TOP RIGHT
#define FLASH_ADDR_COAX 0X00100000
#define FLASH_ADDR_OPT (FLASH_ADDR_COAX + FLASH_32K_SIZE)
#define FLASH_ADDR_RCA (FLASH_ADDR_OPT + FLASH_32K_SIZE)
#define FLASH_ADDR_USB (FLASH_ADDR_RCA + FLASH_32K_SIZE)

// NUM
#define FLASH_ADDR_MUTE 0X00120000
#define FLASH_ADDR_NUM_0 (FLASH_ADDR_MUTE + FLASH_10K_SIZE)
#define FLASH_ADDR_NUM_1 (FLASH_ADDR_NUM_0 + FLASH_5K_SIZE)
#define FLASH_ADDR_NUM_2 (FLASH_ADDR_NUM_1 + FLASH_5K_SIZE)
#define FLASH_ADDR_NUM_3 (FLASH_ADDR_NUM_2 + FLASH_5K_SIZE)
#define FLASH_ADDR_NUM_4 (FLASH_ADDR_NUM_3 + FLASH_5K_SIZE)
#define FLASH_ADDR_NUM_5 (FLASH_ADDR_NUM_4 + FLASH_5K_SIZE)
#define FLASH_ADDR_NUM_6 (FLASH_ADDR_NUM_5 + FLASH_5K_SIZE)
#define FLASH_ADDR_NUM_7 (FLASH_ADDR_NUM_6 + FLASH_5K_SIZE)
#define FLASH_ADDR_NUM_8 (FLASH_ADDR_NUM_7 + FLASH_5K_SIZE)
#define FLASH_ADDR_NUM_9 (FLASH_ADDR_NUM_8 + FLASH_5K_SIZE)
//MENU 2
#define FLASH_ADDR_MENU_2 0X00130000
#define FLASH_ADDR_MENU_2_ADD (FLASH_ADDR_MENU_2 + FLASH_64K_SIZE)
//INPUT OUTPUT
#define FLASH_ADDR_INPUT     (0X00150000)
#define FLASH_ADDR_OUTPUT    (FLASH_ADDR_INPUT + FLASH_32K_SIZE)
#define FLASH_ADDR_BASS      (FLASH_ADDR_OUTPUT + FLASH_32K_SIZE)
#define FLASH_ADDR_TREBLE    (FLASH_ADDR_BASS + FLASH_32K_SIZE)
#define FLASH_ADDR_INP_COAX  0X00170000
#define FLASH_ADDR_INP_RCA   (FLASH_ADDR_INP_COAX + FLASH_8K_SIZE)
#define FLASH_ADDR_INP_USB   (FLASH_ADDR_INP_RCA + FLASH_8K_SIZE)
#define FLASH_ADDR_INP_OPT   (FLASH_ADDR_INP_USB + FLASH_8K_SIZE)
#define FLASH_ADDR_OUT_PO    (FLASH_ADDR_INP_OPT + FLASH_8K_SIZE)
#define FLASH_ADDR_OUT_LO    (FLASH_ADDR_OUT_PO + FLASH_8K_SIZE)
#define FLASH_ADDR_OUT_R_X   (FLASH_ADDR_OUT_LO + FLASH_8K_SIZE)
#define FLASH_ADDR_DOT_GRAY  (FLASH_ADDR_OUT_R_X + FLASH_8K_SIZE)
#define FLASH_ADDR_DOT_ORANGE (FLASH_ADDR_DOT_GRAY + FLASH_1K_SIZE)

#define FLASH_ADDR_INP_COAX_NA    0x00190000
#define FLASH_ADDR_INP_RCA_NA     (FLASH_ADDR_INP_COAX_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_INP_USB_NA     (FLASH_ADDR_INP_RCA_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_INP_OPT_NA     (FLASH_ADDR_INP_USB_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_OUT_PO_NA      (FLASH_ADDR_INP_OPT_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_OUT_LO_NA      (FLASH_ADDR_OUT_PO_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_OUT_R_X_NA     (FLASH_ADDR_OUT_LO_NA + FLASH_8K_SIZE)

#define FLASH_ADDR_LIT_NUM_0  0x001A0000
#define FLASH_ADDR_LIT_NUM_1  (FLASH_ADDR_LIT_NUM_0 + FLASH_2K_SIZE)
#define FLASH_ADDR_LIT_NUM_2  (FLASH_ADDR_LIT_NUM_1 + FLASH_2K_SIZE)
#define FLASH_ADDR_LIT_NUM_3  (FLASH_ADDR_LIT_NUM_2 + FLASH_2K_SIZE)
#define FLASH_ADDR_LIT_NUM_4  (FLASH_ADDR_LIT_NUM_3 + FLASH_2K_SIZE)
#define FLASH_ADDR_LIT_NUM_5  (FLASH_ADDR_LIT_NUM_4 + FLASH_2K_SIZE)
#define FLASH_ADDR_LIT_NUM_6  (FLASH_ADDR_LIT_NUM_5 + FLASH_2K_SIZE)
#define FLASH_ADDR_LIT_NUM_7  (FLASH_ADDR_LIT_NUM_6 + FLASH_2K_SIZE)
#define FLASH_ADDR_LIT_NUM_8  (FLASH_ADDR_LIT_NUM_7 + FLASH_2K_SIZE)
#define FLASH_ADDR_LIT_NUM_9  (FLASH_ADDR_LIT_NUM_8 + FLASH_2K_SIZE)
#define FLASH_ADDR_MINUS      (FLASH_ADDR_LIT_NUM_9 + FLASH_2K_SIZE)

#define FLASH_ADDR_dB      (FLASH_ADDR_MINUS + FLASH_8K_SIZE)
#define FLASH_ADDR_dB_NA   (FLASH_ADDR_dB + FLASH_8K_SIZE)

#define FLASH_ADDR_MENU_3   0x001B0000
#define FLASH_ADDR_MENU_3_ADD (FLASH_ADDR_MENU_3 + FLASH_64K_SIZE)

#define FLASH_ADDR_GAIN        0x001D0000
#define FLASH_ADDR_UAC         (FLASH_ADDR_GAIN + FLASH_32K_SIZE)
#define FLASH_ADDR_FILT        (FLASH_ADDR_UAC + FLASH_32K_SIZE)
#define FLASH_ADDR_MENU3_TONE  (FLASH_ADDR_FILT + FLASH_32K_SIZE)

#define FLASH_ADDR_GAIN_H       0x001F0000
#define FLASH_ADDR_GAIN_H_NA    (FLASH_ADDR_GAIN_H + FLASH_8K_SIZE)
#define FLASH_ADDR_GAIN_L       (FLASH_ADDR_GAIN_H_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_GAIN_L_NA    (FLASH_ADDR_GAIN_L + FLASH_8K_SIZE)
#define FLASH_ADDR_GAIN_M       (FLASH_ADDR_GAIN_L_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_GAIN_M_NA    (FLASH_ADDR_GAIN_M + FLASH_8K_SIZE)

#define FLASH_ADDR_UAC_1       0x00200000
#define FLASH_ADDR_UAC_1_NA    (FLASH_ADDR_UAC_1 + FLASH_8K_SIZE)
#define FLASH_ADDR_UAC_2       (FLASH_ADDR_UAC_1_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_UAC_2_NA    (FLASH_ADDR_UAC_2 + FLASH_8K_SIZE)

#define FLASH_ADDR_TONE_NO       0x00210000
#define FLASH_ADDR_TONE_NO_NA    (FLASH_ADDR_TONE_NO + FLASH_8K_SIZE)
#define FLASH_ADDR_TONE_YES      (FLASH_ADDR_TONE_NO_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_TONE_YES_NA   (FLASH_ADDR_TONE_YES + FLASH_8K_SIZE)

#define FLASH_ADDR_FILT_0       0x00220000
#define FLASH_ADDR_FILT_1       (FLASH_ADDR_FILT_0 + FLASH_8K_SIZE)
#define FLASH_ADDR_FILT_2       (FLASH_ADDR_FILT_1 + FLASH_8K_SIZE)
#define FLASH_ADDR_FILT_3       (FLASH_ADDR_FILT_2 + FLASH_8K_SIZE)
#define FLASH_ADDR_FILT_4       (FLASH_ADDR_FILT_3 + FLASH_8K_SIZE)
#define FLASH_ADDR_FILT_5       (FLASH_ADDR_FILT_4 + FLASH_8K_SIZE)

#define FLASH_ADDR_FILT_0_NA    0x00230000
#define FLASH_ADDR_FILT_1_NA    (FLASH_ADDR_FILT_0_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_FILT_2_NA    (FLASH_ADDR_FILT_1_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_FILT_3_NA    (FLASH_ADDR_FILT_2_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_FILT_4_NA    (FLASH_ADDR_FILT_3_NA + FLASH_8K_SIZE)
#define FLASH_ADDR_FILT_5_NA    (FLASH_ADDR_FILT_4_NA + FLASH_8K_SIZE)

#define FLASH_ADDR_AUTO              0x00240000
#define FLASH_ADDR_LCD_BRIGHTNESS    (FLASH_ADDR_AUTO + FLASH_16K_SIZE)
#define FLASH_ADDR_LOGO              (FLASH_ADDR_LCD_BRIGHTNESS + FLASH_16K_SIZE)
#define FLASH_ADDR_OFF               (FLASH_ADDR_LOGO + FLASH_16K_SIZE)
#define FLASH_ADDR_2MIN              (FLASH_ADDR_OFF + FLASH_16K_SIZE)
#define FLASH_ADDR_PERCENT_25        (FLASH_ADDR_2MIN + FLASH_8K_SIZE)
#define FLASH_ADDR_PERCENT_50        (FLASH_ADDR_PERCENT_25 + FLASH_8K_SIZE)
#define FLASH_ADDR_PERCENT_75        (FLASH_ADDR_PERCENT_50 + FLASH_8K_SIZE)
#define FLASH_ADDR_PERCENT_100       (FLASH_ADDR_PERCENT_75 + FLASH_8K_SIZE)
#define FLASH_ADDR_YES               (FLASH_ADDR_PERCENT_100 + FLASH_8K_SIZE)
#define FLASH_ADDR_NO                (FLASH_ADDR_YES + FLASH_8K_SIZE)

#define FLASH_ADDR_MENU_4           0X00270000
#define FLASH_ADDR_MENU_4_ADD       (FLASH_ADDR_MENU_4 + FLASH_64K_SIZE)
#define FLASH_ADDR_MENU_5           (FLASH_ADDR_MENU_4_ADD + FLASH_64K_SIZE)
#define FLASH_ADDR_MENU_5_ADD       (FLASH_ADDR_MENU_5 + FLASH_64K_SIZE)


#define COORD_TOP_LEFT_X 6
#define COORD_TOP_LEFT_Y 6

#define COORD_TOP_RIGHT_X 120
#define COORD_TOP_RIGHT_Y 6

#define COORD_BOT_LEFT_X 6
#define COORD_BOT_LEFT_Y 120

#define COORD_BOT_RIGHT_X 120
#define COORD_BOT_RIGHT_Y 120

#define COORD_NUM_ONES_X 122
#define COORD_NUM_ONES_Y 85
#define COORD_NUM_TENS_X 78
#define COORD_NUM_TENS_Y 85
#define COORD_NUM_MID_X 100

#define COORD_LIT_NUM_ONES_X 120
#define COORD_LIT_NUM_ONES_Y 105
#define COORD_LIT_NUM_TENS_X 100
#define COORD_LIT_NUM_TENS_Y 105
#define COORD_LIT_NUM_MID_X 110

#define COORD_MINUS_X 80
#define COORD_MINUS_Y 105

#define COORD_DB_X  60
#define COORD_DB_Y  105

#define COORD_MUTE_X    80
#define COORD_MUTE_Y    88

#define COORD_OPTION_X    60
#define COORD_OPTION_Y    105

#define COORD_DOT1_POS_X 101
#define COORD_DOT1_POS_Y 167

#define COORD_DOT2_POS_X 123
#define COORD_DOT2_POS_Y 167

#define FLASH_ADDR_BLOCK1 0X00000000
#define FLASH_ADDR_SECTOR1 0X00000000

#define FLASH_STMP 0XFEFEFEFE

#define FLASH_CS_ENABLE gpio_bit_reset(GPIO_FLASH_CS_PORT, GPIO_FLASH_CS_PIN)
#define FLASH_CS_DISABLE gpio_bit_set(GPIO_FLASH_CS_PORT, GPIO_FLASH_CS_PIN)

typedef enum
{
    FLASH_PICTURE_IDX_BACKGROUND_TEST,
    //MENU 1
    FLASH_PICTURE_IDX_MENU_1,
    FLASH_PICTURE_IDX_MENU_1_ADD,
    // BOT LEFT
    FLASH_PICTURE_IDX_LO,
    FLASH_PICTURE_IDX_PO,
    FLASH_PICTURE_IDX_R_X,
    // BOT RIGHT
    FLASH_PICTURE_IDX_TONE,
    FLASH_PICTURE_IDX_TONE_2,
    FLASH_PICTURE_IDX_VOL,
    FLASH_PICTURE_IDX_VOL_2,
    // TOP LEFT
    FLASH_PICTURE_IDX_DSD_64,
    FLASH_PICTURE_IDX_DSD_128,
    FLASH_PICTURE_IDX_DSD_256,
    FLASH_PICTURE_IDX_DSD_512,
    FLASH_PICTURE_IDX_PCM_44,
    FLASH_PICTURE_IDX_PCM_48,
    FLASH_PICTURE_IDX_PCM_88,
    FLASH_PICTURE_IDX_PCM_96,
    FLASH_PICTURE_IDX_PCM_176,
    FLASH_PICTURE_IDX_PCM_192,
    FLASH_PICTURE_IDX_PCM_352,
    FLASH_PICTURE_IDX_PCM_384,
    FLASH_PICTURE_IDX_PCM_705,
    FLASH_PICTURE_IDX_PCM_768,
    // TOP RIGHT
    FLASH_PICTURE_IDX_COAX,
    FLASH_PICTURE_IDX_OPT,
    FLASH_PICTURE_IDX_RCA,
    FLASH_PICTURE_IDX_USB,
    // NUM
    FLASH_PICTURE_IDX_MUTE,
    FLASH_PICTURE_IDX_NUM_0,
    FLASH_PICTURE_IDX_NUM_1,
    FLASH_PICTURE_IDX_NUM_2,
    FLASH_PICTURE_IDX_NUM_3,
    FLASH_PICTURE_IDX_NUM_4,
    FLASH_PICTURE_IDX_NUM_5,
    FLASH_PICTURE_IDX_NUM_6,
    FLASH_PICTURE_IDX_NUM_7,
    FLASH_PICTURE_IDX_NUM_8,
    FLASH_PICTURE_IDX_NUM_9,
    //MENU 2
    FLASH_PICTURE_IDX_MENU_2,
    FLASH_PICTURE_IDX_MENU_2_ADD,
    //INPUT OUTPUT
     FLASH_PICTURE_IDX_INPUT,
    FLASH_PICTURE_IDX_OUTPUT,
    FLASH_PICTURE_IDX_BASS,
    FLASH_PICTURE_IDX_TREBLE,

    FLASH_PICTURE_IDX_INP_COAX,
    FLASH_PICTURE_IDX_INP_USB,
    FLASH_PICTURE_IDX_INP_OPT,
    FLASH_PICTURE_IDX_INP_RCA,
    FLASH_PICTURE_IDX_OUT_PO,
    FLASH_PICTURE_IDX_OUT_R_X,
    FLASH_PICTURE_IDX_OUT_LO,
    FLASH_PICTURE_IDX_DOT_GRAY,
    FLASH_PICTURE_IDX_DOT_ORANGE,

    FLASH_PICTURE_IDX_INP_COAX_NA,
    FLASH_PICTURE_IDX_INP_USB_NA,
    FLASH_PICTURE_IDX_INP_OPT_NA,
    FLASH_PICTURE_IDX_INP_RCA_NA,
    FLASH_PICTURE_IDX_OUT_PO_NA,
    FLASH_PICTURE_IDX_OUT_R_X_NA,
    FLASH_PICTURE_IDX_OUT_LO_NA,

    FLASH_PICTURE_IDX_LIT_NUM_0,
    FLASH_PICTURE_IDX_LIT_NUM_1,
    FLASH_PICTURE_IDX_LIT_NUM_2,
    FLASH_PICTURE_IDX_LIT_NUM_3,
    FLASH_PICTURE_IDX_LIT_NUM_4,
    FLASH_PICTURE_IDX_LIT_NUM_5,
    FLASH_PICTURE_IDX_LIT_NUM_6,
    FLASH_PICTURE_IDX_LIT_NUM_7,
    FLASH_PICTURE_IDX_LIT_NUM_8,
    FLASH_PICTURE_IDX_LIT_NUM_9,
    FLASH_PICTURE_IDX_MINUS,
    FLASH_PICTURE_IDX_dB,
    FLASH_PICTURE_IDX_dB_NA,

    FLASH_PICTURE_IDX_MENU_3,
    FLASH_PICTURE_IDX_MENU_3_ADD,

    FLASH_PICTURE_IDX_GAIN,
    FLASH_PICTURE_IDX_UAC,
    FLASH_PICTURE_IDX_FILT,
    FLASH_PICTURE_IDX_MENU3_TONE,
    
    
    FLASH_PICTURE_IDX_GAIN_L,
    FLASH_PICTURE_IDX_GAIN_M,
    FLASH_PICTURE_IDX_GAIN_H,
    FLASH_PICTURE_IDX_GAIN_L_NA,
    FLASH_PICTURE_IDX_GAIN_M_NA,
    FLASH_PICTURE_IDX_GAIN_H_NA,

    FLASH_PICTURE_IDX_UAC_1,
    FLASH_PICTURE_IDX_UAC_2,
    FLASH_PICTURE_IDX_UAC_1_NA,
    FLASH_PICTURE_IDX_UAC_2_NA,

    FLASH_PICTURE_IDX_TONE_NO,
    FLASH_PICTURE_IDX_TONE_YES,
    FLASH_PICTURE_IDX_TONE_NO_NA,
    FLASH_PICTURE_IDX_TONE_YES_NA,

    FLASH_PICTURE_IDX_FILT_0,
    FLASH_PICTURE_IDX_FILT_1,
    FLASH_PICTURE_IDX_FILT_2,
    FLASH_PICTURE_IDX_FILT_3,
    FLASH_PICTURE_IDX_FILT_4,
    FLASH_PICTURE_IDX_FILT_5,
    FLASH_PICTURE_IDX_FILT_0_NA,
    FLASH_PICTURE_IDX_FILT_1_NA,
    FLASH_PICTURE_IDX_FILT_2_NA,
    FLASH_PICTURE_IDX_FILT_3_NA,
    FLASH_PICTURE_IDX_FILT_4_NA,
    FLASH_PICTURE_IDX_FILT_5_NA,

    FLASH_PICTURE_IDX_AUTO,
    FLASH_PICTURE_IDX_LCD_BRIGHTNESS,
    FLASH_PICTURE_IDX_LOGO,
    FLASH_PICTURE_IDX_OFF,
    FLASH_PICTURE_IDX_2MIN,
    FLASH_PICTURE_IDX_PERCENT_25,
    FLASH_PICTURE_IDX_PERCENT_50,
    FLASH_PICTURE_IDX_PERCENT_75,
    FLASH_PICTURE_IDX_PERCENT_100,
    FLASH_PICTURE_IDX_NO,
    FLASH_PICTURE_IDX_YES,
    FLASH_PICTURE_IDX_MENU_4,
    FLASH_PICTURE_IDX_MENU_4_ADD,
    FLASH_PICTURE_IDX_MENU_5,
    FLASH_PICTURE_IDX_MENU_5_ADD,
    FLASH_PICTURE_IDX_INVAL,
} flash_picture_idx_t;

typedef struct
{
    uint16_t width;
    uint16_t height;
    uint32_t addr;
} flash_picture_atrribute_t;

typedef enum
{
    FLASH_ST_IDL,

    FLASH_ST_WRITE_START,
    FLASH_ST_ERASE_WRITE_ENABLE,
    FLASH_ST_ERASE_WRITE_ENABLE_WAIT,
    FLASH_ST_ERASE,
    FLASH_ST_ERASE_WAIT,
    FLASH_ST_ERASE_Read_Status_Register1_BUSY,
    FLASH_ST_ERASE_Read_Status_Register1_BUSY_WAIT,
    FLASH_ST_ERASE_DUMMY,
    FLASH_ST_ERASE_DUMMY_WAIT,
    FLASH_ST_PAGE_PROGRAM_WRITE_ENABLE,
    FLASH_ST_PAGE_PROGRAM_WRITE_ENABLE_WAIT,
    FLASH_ST_PAGE_PROGRAM_INSTRUCTION,
    FLASH_ST_PAGE_PROGRAM_INSTRUCTION_WAIT,
    FLASH_ST_PAGE_PROGRAM_DATA,
    FLASH_ST_PAGE_PROGRAM_DATA_WAIT,
    FLASH_ST_PAGE_PROGRAME_Read_Status_Register1_BUSY,
    FLASH_ST_PAGE_PROGRAME_Read_Status_Register1_BUSY_WAIT,
    FLASH_ST_PAGE_PROGRAME_DUMMY,
    FLASH_ST_PAGE_PROGRAME_DUMMY_WAIT,

    FLASH_ST_READ_DATA_INSTRUCTION,
    FLASH_ST_READ_DATA_INSTRUCTION_WAIT,
    FLASH_ST_READ_DATA_DUMMY,
    FLASH_ST_READ_DATA_DUMMY_WAIT,

    TONE_ST_WRITE_START,
    TONE_ST_WRITE_DATA,
    TONE_ST_WRITE_DATA_WAITING,
    TONE_ST_WRITE_CHA_TREBLE_DATA,
    TONE_ST_WRITE_CHA_TREBLE_DATA_WAITING,
    TONE_ST_WRITE_CHA_BASS_DATA,
    TONE_ST_WRITE_CHA_BASS_DATA_WAITING,
    TONE_ST_WRITE_CHB_TREBLE_DATA,
    TONE_ST_WRITE_CHB_TREBLE_DATA_WAITING,
    TONE_ST_WRITE_CHB_BASS_DATA,
    TONE_ST_WRITE_CHB_BASS_DATA_WAITING,
    TONE_ST_WRITE_COMPLETE,

    FLASH_ST_CHECK_OUT,
} flash_st_t;

typedef struct
{
    uint8_t buf[FLASH_SAVE_BUF_SIZE];
    uint8_t ready_flag;
    uint16_t idx;
    uint16_t length;
} flash_save_buf_t;

typedef struct
{
    uint8_t buf[FLASH_SEND_BUF_SIZE];
    uint16_t idx;
    uint16_t length;

} flash_buf_t;

typedef enum
{
    FLASH_MSG_READ_BACKGROUND,

    FLASH_MSG_WRITE_IDX,
    FLASH_MSG_WRITE_ONLY,

    FLASH_MSG_ERASE_CHIP,
    FLASH_MSG_SECTOR_ERASE,
    FLASH_MSG_BLOCK_ERASE,

    FLASH_MSG_WRITE_TONE,
} flash_msg_st_t;

typedef struct
{
    flash_msg_st_t msg;
    uint8_t *buf_p;
    uint32_t length;
    uint8_t tone_data[2];
    flash_picture_idx_t flash_picture_idx;
} flash_msg_frame_t;

typedef struct
{
    flash_msg_frame_t frame[FLASH_MSG_FRAME_BUF_SIZE];
    uint8_t idx_in;
    uint8_t idx_out;
    uint8_t total;
} flash_msg_qu_t;

typedef struct
{
    uint32_t stmp;
    uint16_t crc_value;
    uint32_t data_length;
} header_t;

typedef struct
{
    uint32_t flash_dma_length;
    uint8_t flash_rx_dma_cplt;
    uint32_t flash_remaining_length;
} flash_to_lcd_t;

typedef struct
{
    uint8_t flash_rx_busy;
    uint8_t flash_tx_busy;
    uint32_t flash_addr_tmp;
    flash_msg_st_t last_msg;
    
} flash_blk_t;

extern flash_st_t flash_st;
extern flash_save_buf_t flash_save_buf1;
extern flash_save_buf_t flash_save_buf2;
extern flash_buf_t flash_tx_buf;
extern flash_buf_t flash_rx_buf;

extern flash_to_lcd_t flash_to_lcd;
extern flash_picture_atrribute_t flash_picture_array[];

extern uint8_t dummy[FLASH_PROGRAM_PAGE_MAX];

void flash_msg_check_in(uint8_t *data, flash_picture_idx_t flash_picture_idx, flash_msg_st_t flash_msg_st);
void flash_task(void *pvParameters);
void flash_spi1_callback(void);
void flash_dma_callback(void);
void flash_tx_dma_config(void);
void flash_rx_dma_config(void);

#endif
