#ifndef __XMOS_H
#define __XMOS_H

#include "stdint.h"

#define XMOS_HEADER     0X55AA
#define XMOS_VERSION    0X01

#define XMOS_DEFAULT_LENGTH 6

#define XMOS_CMD_BOOT   0X00
#define XMOS_CMD_READ_PRODUCT  0X01
#define XMOS_CMD_READ_BOOT_CONFIG   0X02
#define XMOS_CMD_READ_AUDIO_MODE 0X03
#define XMOS_CMD_READ_CLIENT_CONFIG 0X04
#define XMOS_CMD_COMPLETE   0X05

#define XMOS_CMD_SEND_STATUS    0X20
#define XMOS_CMD_SEND_MEDIA_CTRL 0X21
#define XMOS_CMD_SEND_FORMAT    0X22
#define XMOS_CMD_SEND_AUDIO_MODE    0X23
#define XMOS_CMD_SEND_PLAY_VOLUME   0X24
#define XMOS_CMD_SEND_RECORD_VOLUME 0X25

#define XMOS_CMD_SEND_UPDATE_SUCCESS 0X01
#define XMOS_CMD_SEND_UPDATE_FAILURE 0X00
#define XMOS_CMD_SEND_UPDATE_RESTART 0X02

typedef enum
{
    XMOS_CMD_IDX_BOOT,
    XMOS_CMD_IDX_READ_PRODUCT,
    XMOS_CMD_IDX_READ_BOOT_CONFIG,
    XMOS_CMD_IDX_READ_AUDIO_MODE,
    XMOS_CMD_IDX_READ_CLIENT_CONFIG,
    XMOS_CMD_IDX_COMPLETE,

    XMOS_CMD_IDX_SEND_STATUS,
    XMOS_CMD_IDX_SEND_MEDIA_CTRL,
    XMOS_CMD_IDX_SEND_FORMAT,
    XMOS_CMD_IDX_SEND_AUDIO_MODE,
    XMOS_CMD_IDX_SEND_PLAY_VOLUME,
    XMOS_CMD_IDX_SEND_RECORD_VOLUME,

    XMOS_CMD_IDX_UPDATE_PACK_SUCCESS,
    XMOS_CMD_IDX_UPDATE_PACK_FAILURE,
    XMOS_CMD_IDX_UPDATE_PACK_RESTART,
}xmos_cmd_idx_t;

typedef struct 
{
    
    uint8_t cmd;
    char *content;
}xmos_cmd_t;

extern xmos_cmd_t xmos_cmd_array[];

#endif

